[redhat] only define CONFIG_SOUNDWIRE_AMD in common
This config is already set in common and due to 0386d765f27a1
('ASoC: amd: ps: refactor acp device configuration read logic') it now
creates the following error:

Error: Mismatches found in configuration files for x86_64 debug-rhel
Found CONFIG_SOUNDWIRE_AMD=m after generation, had CONFIG_SOUNDWIRE_AMD=is not set in Source tree
Error: Mismatches found in configuration files for x86_64 rhel
Found CONFIG_SOUNDWIRE_AMD=m after generation, had CONFIG_SOUNDWIRE_AMD=is not set in Source tree

Signed-off-by: Scott Weaver <scweaver@redhat.com>