redhat: Fix macro for kernel-uki-virt flavor
When the versioned systemd dependency was dropped, the structure for
the macro was accidentally broken, resulting in the error:

error: kernel.spec: line 1522: %endif with no %if

This change puts back the missing backslash that makes the macro
evaluate properly again.

Fixes: be6000d0869de113ce64b84cfd420581d69c5d29 ("Change the uki reqs for Fedora")

Signed-off-by: Neal Gompa <ngompa@fedoraproject.org>