Add python3-setuptools buildreq for perf
With the 6.0 updates for perf, the build fails with a missing
ModuleNotFoundError: No module named 'setuptools' if we don't have
python3-setuptools as a buildreq.

Signed-off-by: Justin M. Forbes <jforbes@fedoraproject.org>