gitlab-ci: merge-linux-next: workaround pydantic-core build error
The rawhide builder includes python 3.14 but the anthropic and
google-generativeai python packages depend on the pydantic-core package
which requires PyO3 and that does not yet support 3.14.

error: the configured Python interpreter version (3.14) is newer than
PyO3's maximum supported version (3.13)

To workaround this, let's use the stream10 builder until we can install
compatible versions.

Signed-off-by: Scott Weaver <scweaver@redhat.com>